electrical_data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
electrical_data$Date<-as.Date(electrical_data$Date,"%d/%m/%Y")
data<-subset(electrical_data,Date>='2007-02-01' & Date<='2007-02-02')
data$Date<-as.character(data$Date)
data$Date_Time<-as.POSIXct(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")
data$Sub_metering_1<-as.character(data$Sub_metering_1)
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.character(data$Sub_metering_2)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.character(data$Sub_metering_3)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)

with(data,plot(Date_Time,Sub_metering_1,xlab="",ylab="Energy sub metering",type="n"))
with(data,points(Date_Time,Sub_metering_1,type="l"))
with(data,points(Date_Time,Sub_metering_2,type="l",col="red"))
with(data,points(Date_Time,Sub_metering_3,type="l",col="blue"))
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"))
dev.copy(png,"plot3.png")
dev.off()