electrical_data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
electrical_data$Date<-as.Date(electrical_data$Date,"%d/%m/%Y")
data<-subset(electrical_data,Date>='2007-02-01' & Date<='2007-02-02')
data$Global_active_power<-as.character(data$Global_active_power)
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Date<-as.character(data$Date)
data$Date_Time<-as.POSIXct(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")
with(data,plot(Date_Time,Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)"))
dev.copy(png,"plot2.png")
dev.off()